In [2]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import sys
import os

# 添加项目根目录到路径
# 在 Jupyter Notebook (.ipynb) 中，__file__ 变量未定义，使用 sys.argv[0] 或直接指定路径的替代方案
import inspect
try:
    # 尝试获取当前文件路径
    frame = inspect.currentframe()
    if frame is not None:
        filename = inspect.getfile(frame)
        sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(filename))))
except:
    # 如果获取失败，可根据实际情况调整，这里假设 notebook 在 example 目录下
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(''))))
# 使用相对 imports (从子目录直接导入)
from charts.seasonal_chart import SeasonalChart
from charts.time_series_chart import TimeSeriesChart
from utils.data_formatter import DataFormatter
from utils.template_manager import TemplateManager
from core.wind_client import WindClient
from core.data_processor import DataProcessor
from core.akshare_client import AkShareClient
import akshare as ak

In [ ]:

def demo_akshare_data():
    """演示akshare数据获取"""
    if not AKSHARE_AVAILABLE:
        print("\n=== akshare数据演示 (不可用) ===")
        print("请先安装akshare: pip install akshare")
        return None
    
    print("\n=== akshare数据演示 ===")
    
    try:
        # 获取股票数据示例
        print("正在获取股票数据...")
        stock_df = AkShareClient.get_demo_data("stock", 365)
        print(f"✓ 获取股票数据成功: {len(stock_df)}条记录")
        print(f"  数据范围: {stock_df['date'].min()} 到 {stock_df['date'].max()}")
        
        # 获取指数数据示例
        print("正在获取指数数据...")
        index_df = AkShareClient.get_demo_data("index", 365)
        print(f"✓ 获取指数数据成功: {len(index_df)}条记录")
        
        # 显示可用代码
        print("\n可用股票代码示例:")
        stock_symbols = AkShareClient.list_available_symbols("stock")
        print(f"  前10个股票代码: {stock_symbols[:10]}")
        
        print("\n可用指数代码示例:")
        index_symbols = AkShareClient.list_available_symbols("index")
        print(f"  主要指数代码: {index_symbols[:5]}")
        
        return stock_df
        
    except Exception as e:
        print(f"❌ akshare数据获取失败: {str(e)}")
        print("将使用模拟数据继续演示")
        return None

In [6]:
def demo_akshare_seasonal():
    """使用akshare数据进行季节性分析演示"""
    if not AKSHARE_AVAILABLE:
        print("akshare不可用，使用模拟数据")
        return generate_comprehensive_data()
    
    try:
        # 获取平安银行股票数据
        end_date = datetime.now().strftime('%Y%m%d')
        start_date = (datetime.now() - timedelta(days=730)).strftime('%Y%m%d')
        
        df = AkShareClient.get_stock_daily("000001", start_date, end_date)
        
        # 为演示添加更多字段
        df['inventory'] = df['close'] * 100 + np.random.normal(0, 100, len(df))
        df['production'] = df['close'] * 80 + np.random.normal(0, 50, len(df))
        
        print(f"✓ 使用akshare真实数据: {len(df)}条记录")
        return df
        
    except Exception as e:
        print(f"akshare数据获取失败，使用模拟数据: {e}")
        return generate_comprehensive_data()
        
df = demo_akshare_seasonal()

✓ 使用akshare真实数据: 484条记录

In [8]:
df

          date   open   high    low  close   volume    inventory   production
0   2023-07-26  11.65  11.74  11.56  11.67   751663  1087.646627   933.686001
1   2023-07-27  11.68  11.87  11.65  11.75  1115196  1143.089515   897.736965
2   2023-07-28  11.69  12.30  11.67  12.26  2347013  1034.758387   924.359637
3   2023-07-31  12.30  12.50  12.23  12.32  1854952  1182.318690   903.371232
4   2023-08-01  12.26  12.37  12.13  12.16   957735  1260.306695  1010.069539
..         ...    ...    ...    ...    ...      ...          ...          ...
479 2025-07-18  12.62  12.75  12.60  12.70  1241206  1048.101838  1020.294689
480 2025-07-21  12.64  12.71  12.55  12.61  1079027  1310.171294   981.912927
481 2025-07-22  12.60  12.60  12.32  12.49  1935229  1252.911954  1018.037553
482 2025-07-23  12.46  12.63  12.45  12.53  1370520  1233.959040  1004.336959
483 2025-07-24  12.53  12.53  12.33  12.35  1959351  1245.071974  1020.644232

[484 rows x 8 columns]